# Generated by Django 5.0 on 2023-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_userprofile_id_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forgot',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
